name: Release

on:
  push:
    branches:
      - main

jobs:
  # The "Changelog" job creates a new release draft on GitHub.
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Update Changelog
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release.yaml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
